export interface Assumption {
  id: string;
  label: string;
  symbol: string;
  defaultValue: number;
  unit: string;
  min: number;
  max: number;
  step: number;
  citation: string;
  description: string;
  tab: 'macro' | 'trade' | 'banking' | 'distribution' | 'global';
}

export const ASSUMPTIONS: Assumption[] = [
  {
    id: 'piStar',
    label: 'Inflation Target',
    symbol: 'π*',
    defaultValue: 2,
    unit: '%',
    min: 0,
    max: 8,
    step: 0.5,
    citation: 'Taylor (1993); Bernanke & Mishkin (1997)',
    description: 'The central bank\'s long-run inflation objective. 2% is the standard in advanced economies.',
    tab: 'macro',
  },
  {
    id: 'rStarWorld',
    label: 'World Neutral Real Rate',
    symbol: 'r*',
    defaultValue: 2,
    unit: '%',
    min: 0,
    max: 5,
    step: 0.25,
    citation: 'Laubach & Williams (2003); Holston et al. (2017)',
    description: 'The real interest rate consistent with output at potential and stable inflation. Has trended downward since the 1990s.',
    tab: 'macro',
  },
  {
    id: 'lambda',
    label: 'Expectations Adaptation',
    symbol: 'λ',
    defaultValue: 0.4,
    unit: '',
    min: 0.1,
    max: 0.9,
    step: 0.05,
    citation: 'Sargent (1971); Fuhrer (1997)',
    description: 'Speed at which inflation expectations update toward realized inflation. Higher = more backward-looking.',
    tab: 'macro',
  },
  {
    id: 'phiPi',
    label: 'Taylor Inflation Coefficient',
    symbol: 'φπ',
    defaultValue: 1.5,
    unit: '',
    min: 1.0,
    max: 3.0,
    step: 0.25,
    citation: 'Taylor (1993)',
    description: 'Governs how aggressively the central bank raises rates when inflation exceeds target. Must exceed 1 (Taylor Principle).',
    tab: 'macro',
  },
  {
    id: 'phiY',
    label: 'Taylor Output Gap Coefficient',
    symbol: 'φy',
    defaultValue: 0.5,
    unit: '',
    min: 0,
    max: 1.5,
    step: 0.25,
    citation: 'Taylor (1993); Orphanides (2003)',
    description: 'How much the central bank weights output stabilization relative to inflation. Original Taylor rule uses 0.5.',
    tab: 'macro',
  },
  {
    id: 'sigmaEps',
    label: 'Inflation Shock Std. Dev.',
    symbol: 'σε',
    defaultValue: 0.4,
    unit: '%',
    min: 0.1,
    max: 1.5,
    step: 0.1,
    citation: 'Smets & Wouters (2007)',
    description: 'Standard deviation of monthly supply-side inflation shocks (cost-push, commodity). Annualizes to ~1.4pp.',
    tab: 'macro',
  },
  {
    id: 'theta',
    label: 'Trade Elasticity',
    symbol: 'θ',
    defaultValue: 4,
    unit: '',
    min: 2,
    max: 8,
    step: 0.5,
    citation: 'Anderson & van Wincoop (2003); Head & Mayer (2014)',
    description: 'Armington elasticity of substitution between trade partners. Higher = goods are more substitutable.',
    tab: 'trade',
  },
  {
    id: 'crisisThreshold',
    label: 'Crisis Leverage Threshold',
    symbol: 'λ̄',
    defaultValue: 12,
    unit: 'x',
    min: 8,
    max: 20,
    step: 1,
    citation: 'Minsky (1986); Reinhart & Rogoff (2009)',
    description: 'Banking sector leverage ratio above which a financial crisis is triggered. Lower = more fragile system.',
    tab: 'banking',
  },
  {
    id: 'nuNW',
    label: 'Net Worth Recovery Speed',
    symbol: 'νNW',
    defaultValue: 0.05,
    unit: '',
    min: 0.01,
    max: 0.15,
    step: 0.01,
    citation: 'Bernanke, Gertler & Gilchrist (1999)',
    description: 'Rate at which banking sector net worth mean-reverts to its steady state after a shock.',
    tab: 'banking',
  },
  {
    id: 'betaV',
    label: 'Velocity Sensitivity',
    symbol: 'βv',
    defaultValue: 0.15,
    unit: '',
    min: 0,
    max: 0.5,
    step: 0.05,
    citation: 'Bordo & Jonung (1990); Carstens (2019)',
    description: 'How much money velocity falls when inflation expectations rise. Captures flight-to-quality under digital scarcity.',
    tab: 'macro',
  },
  {
    id: 'reserveRatio',
    label: 'Reserve Backing Ratio',
    symbol: 'ρ',
    defaultValue: 0.3,
    unit: '',
    min: 0.1,
    max: 1.0,
    step: 0.05,
    citation: 'Diem Association (2019); IMF (2022)',
    description: 'Fraction of digital currency supply backed by fiat reserves. 1.0 = fully backed stablecoin.',
    tab: 'macro',
  },
  {
    id: 'tfpGrowth',
    label: 'TFP Growth (Annual)',
    symbol: 'g_A',
    defaultValue: 2,
    unit: '%',
    min: 0,
    max: 5,
    step: 0.25,
    citation: 'Fernald (2015); Gordon (2016)',
    description: 'Trend total factor productivity growth rate. Applied as 1/12 monthly to each country\'s potential output.',
    tab: 'macro',
  },
];
